customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
gui:
  mouseEvents: false
os:
  editPreset: 'nvim'
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} {{filename}}'
