#
# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#
# Terminal multiplexer
# https://github.com/tmux/tmux

source-file ~/.config/tmux/tmux.reset.conf

# -- General Settings ----------------------------------------------------------
set -g default-shell /usr/bin/fish
set -g mouse on               
set -g prefix ^A
set -g base-index 1          
set -g detach-on-destroy off
set -g escape-time 0       
set -g history-limit 1000000     
set -g renumber-windows on      
set -g set-clipboard on        
setw -g mode-keys vi
set -g status-keys vi
set -gu default-command $SHELL
set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -g visual-activity off
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ga update-environment "FZF_DEFAULT_OPTS"

set -gq utf8 on
set -gq status-utf8 on

# -- Visuals --------------------------------------------------------
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ",*256col*:Tc" # true color support
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[ q' # blinking cursor?
set -ga terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -ga terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
set -as terminal-features ",xterm-kitty:RGB"

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'


set -g automatic-rename on
# set -g automatic-rename-format "#{window_icon} #{b:pane_current_command}"

# -- Plugins --------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
# set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# -- Statusbar Plugin -------------------------------------------------------
set -g @statusbar_flavor "storm" #storm, night, or neon
set -g @statusbar_status_background "none" #theme or none (transparent)
set -g @statusbar_pane_dim "yes"          # Dim inactive panes
set -g @statusbar_pane_borders "yes"      # Neon pane borders
set -g @statusbar_popup "yes"
set -g @statusbar_messages "yes"
run '~/.config/tmux/plugins/statusbar/statusbar.tmux'

set -g @plugin 'tmux-plugins/tpm'

# -- Theme --------------------------------------------------------------------
source-file ~/.config/tmux/generated.conf

# -- Status Bar -----------------------------------------------------------------
set -g status-position top
set-option -g set-titles on
set-option -gw pane-border-indicators 'colour'
set-option -g pane-border-lines single
set -g status "on"
set -g status-interval 3

run '~/.config/tmux/plugins/tpm/tpm'
