m script-binding uosc/menu
tab script-binding uosc/toggle-ui
s script-binding uosc/subtitles
b script-binding uosc/download-subtitles
> script-binding uosc/next-file
< script-binding uosc/prev-file
a script-binding uosc/audio          
q script-binding uosc/stream-quality  
c script-binding uosc/chapters
p script-binding uosc/items
P script-binding uosc/toggle-progress
alt+i script-binding uosc/keybinds 


ESC set pause yes; set fullscreen no; set window-minimized yes
ctrl+s      async screenshot 

AXIS_UP add volume 2
AXIS_DOWN add volume -2
UP add volume 2
DOWN add volume -2
y cycle deband
z cycle deband


###
### Recents script
###

Ctrl+r script-message-to recent display
