cursor #e5e1e4
cursor_text_color #c7c5ce
foreground            #e5e1e4
background            #131315
selection_foreground  #2e303a
selection_background  #c6c5d3
url_color             #c1c5e3
os-bg #161a31
medium #39393b



# black
color0   #2a2a2c
color8   #e5e1e4

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #e5e1e4
color10  #c1c5e3

# yellow
color3   #5a3e51
color11  #fed8f0

# blue
color4  #c1c5e3
color12 #41455f

# magenta
color5   #ffb4ab
color13  #e1bcd3

# cyan
color6   #e5e1e4
color14  #41283a

# white
color7  #39393b
color15 #e5e1e4

# Tab Bar
active_tab_background   #c1c5e3
active_tab_foreground   #2b2f47
inactive_tab_background #201f21
inactive_tab_foreground #c7c5ce
tab_bar_background      #131315

# Window borders
active_border_color   #c1c5e3
inactive_border_color #201f21
