cursor #e6e1e7
cursor_text_color #cbc4d0
foreground            #e6e1e7
background            #141317
selection_foreground  #342c44
selection_background  #cdc1df
url_color             #d2bbff
os-bg #230e49
medium #3b383d



# black
color0   #2b292e
color8   #e6e1e7

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #e6e1e7
color10  #d2bbff

# yellow
color3   #6d3355
color11  #ffd8ea

# blue
color4  #d2bbff
color12 #4f3c77

# magenta
color5   #ffb4ab
color13  #fdafd8

# cyan
color6   #e6e1e7
color14  #521c3e

# white
color7  #3b383d
color15 #e6e1e7

# Tab Bar
active_tab_background   #d2bbff
active_tab_foreground   #38255f
inactive_tab_background #211f23
inactive_tab_foreground #cbc4d0
tab_bar_background      #141317

# Window borders
active_border_color   #d2bbff
inactive_border_color #211f23
